### ISSUE TITLE
PB fiche user

### ISSUE THREAD

**Issue by CFJJB** [thibaultvanc/cfjjb_recettage#11]
je ne peux plus consulter de fiche users dans le back office

**Comment by thibaultvanc** [comment]
Quel backoffice ? de mon c'est bon . merci de preciser ou cloture l'issue si ok

**Comment by CFJJB** [comment]
il ne s'agit pas de toutes les fiches users, certaines sont consultables et d'autres pas.

**Comment by thibaultvanc** [comment]
corrigé
