### ISSUE TITLE
PB paniers et commandes licences en CB

### ISSUE THREAD

**Issue by CFJJB** [thibaultvanc/cfjjb_recettage#13]
j'ai fait 2 commandes pour gracie barra côtes d'azur via le compte club. (1 en chèque et une en CB)

Seulement les paniers ne sont pas consultables dans le back office "message d'erreur"

Et la commande effectuée en paiement CB apparait comme non payée dans le back office alors que j'ai bien effectué le paiement CB "test"

**Comment by thibaultvanc** [comment]
ok  fait - merci de rester
