### ISSUE TITLE
problème des teams

### ISSUE THREAD

**Issue by CFJJB** [thibaultvanc/cfjjb_recettage#8]
le nom de la team dont le club fait partie, n'apparait pas sur la liste des inscrit et n'apparait pas non plus sur les brackets.

c'est que le club qui apparait, hors ça doit être la team qui apparait par défaut et si le club ne fait pas partie d'une team alors c'est club qui apparait

**Comment by thibaultvanc** [comment]
note interne : le pb viens de l'enregistrement - pas de l'affichage

**Comment by CFJJB** [comment]
c'est normal que le slider il saute à chaque j'ai du le remettre tout à l'heure et là il est encore parti
