### ISSUE TITLE
PB affichage des teams

### ISSUE THREAD

**Issue by CFJJB** [thibaultvanc/cfjjb_recettage#9]
j'ai crée une compet test "CPT TEST 2018" ; en paiement partagé.
donc il y en une Gi et une en No-Gi.

- Sur la liste des participants en Gi aucun PB les team s'affiche
- Sur la liste des participants No-Gi les Teams ne s'affichent pas correctement : tu peux voir que david est sur la team gracie barra alors que stéphane apparait sur gracie barra côte d'azur.
Tu peux voir aussi que Fernandez et Jardin apparaissent sur leur club et pas sur leur team.
voir lien suivant : http://cfjjbv2.organit.fr/competition/161
- Idem sur les scoring brackets

- je reprécise que cela concerne la partie "No-Gi" ; en Gi"" aucun PB

**Comment by thibaultvanc** [comment]
A retester .
il faut re-inscrire pour que ca marche !!

**Comment by CFJJB** [comment]
dsl j'ai fait la manip mais toujours pas ok de mon coté : http://cfjjbv2.organit.fr/competition/161

idem sur les scoring brackets

**Comment by thibaultvanc** [comment]
de mon coté c'est bon, reesaye. si tu l'a pas, on partage ecran

**Comment by thibaultvanc** [comment]
si payement annulé aussi
